Repository rocky-linux/rockylinux.org, pull requests merged in 2020-12, with the labels that each got.

#3 feat: improve contrast of dark mode "go home" btn
  layouts/404.html
Labels: enhancement

#8 docs: include contribution guidelines
  CONTRIBUTING.md
Labels: enhancement

#5 Change absolute paths for relative paths.
  README.md
  config.toml
  layouts/index.html
  layouts/partials/footer/footer.html
  layouts/partials/head/head.html
  package-lock.json
  package.json
  public/404.html
  public/index.html
Labels: enhancement

#19 Add multilanguaje option.
  config.toml
  i18n/en.toml
  i18n/es.toml
  layouts/404.html
  layouts/index.html
  layouts/partials/footer/footer.html
Labels: enhancement

#20 docs: Updated README
  README.md
Labels: documentation

#31 improvement: updated get involved link
  config.toml
Labels: documentation, enhancement

#32 fix: vercel i18n 404
  layouts/404.html
  vercel.json
Labels: bug

#59 minor stylistic changes for a better daily Turkish
  i18n/tr.toml
Labels: translation

#40 Add Dutch (nl) translation
  config.toml
  i18n/nl.toml
  layouts/partials/head/head.html
  vercel.json
Labels: translation

#41 Added Brazilian Portuguese language support
  config.toml
  i18n/pt-BR.toml
  layouts/partials/head/head.html
  vercel.json
Labels: translation

#43 Add missing part for de translation
  i18n/de.toml
  layouts/partials/head/head.html
Labels: translation

#49 add Simplified Chinese(zh_CN) translation
  config.toml
  i18n/zh.toml
  layouts/partials/head/head.html
  vercel.json
Labels: translation

#51 Add Japanese (ja) translation
  config.toml
  i18n/ja.toml
  layouts/partials/head/head.html
  vercel.json
Labels: translation

#54 Improve Italian translation
  i18n/it.toml
Labels: translation

#81 Fixed language redirect and made it dynamic.
  config.toml
  i18n/pt-PT.toml
  layouts/partials/head/head.html
  vercel.json
Labels: enhancement

#63 Fixes For Turkish Translation
  i18n/tr.toml
Labels: translation

#67 adding Arabic language
  config.toml
  i18n/ar.toml
  layouts/partials/head/head.html
  vercel.json
Labels: translation

#88 Fixed some typos, translation improvement.
  i18n/pl.toml
Labels: translation

#93 Russian translation improvements
  i18n/ru.toml
Labels: translation

#95 Adding Persian (fa) translation
  config.toml
  i18n/fa.toml
  vercel.json
Labels: translation

#91 Add Indonesian (id) translation
  config.toml
  i18n/id.toml
  vercel.json
Labels: translation

#96 Add Korean(ko) translation
  config.toml
  i18n/ko.toml
  vercel.json
Labels: translation

#100 Add French (fr) translation
  config.toml
  i18n/fr.toml
  vercel.json
Labels: translation

#101 Adding Right-to-Left support
  layouts/404.html
  layouts/index.html
  layouts/partials/footer/footer.html
Labels: enhancement, translation

#115 Enhanced Persian (fa) translation
  i18n/fa.toml
Labels: translation

#112 chore: add Issue+PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: enhancement

#114 Accessibility changes
  layouts/_default/baseof.html
  layouts/index.html
  layouts/partials/footer/footer.html
Labels: enhancement

#138 Diverse translation improvements to es.toml
  i18n/es.toml
Labels: translation

#139 fix the wordings for zh-tw
  i18n/zh-TW.toml
Labels: translation

#140 Update de.toml
  i18n/de.toml
Labels: translation

#137 Add Ukrainian translation
  config.toml
  i18n/uk.toml
  vercel.json
Labels: translation

#148 Improve Ukrainian translation
  i18n/uk.toml
Labels: translation

#160 Fixed typo for Italian language
  i18n/it.toml
Labels: translation

#151 Update es.toml
  i18n/en.toml
  i18n/es.toml
  i18n/nl.toml
  i18n/pl.toml
  i18n/pt-BR.toml
  i18n/pt-PT.toml
Labels: translation

#150 Diverse translation improvements to sv.toml
  config.toml
  i18n/sv.toml
  layouts/partials/head/head.html
  vercel.json
Labels: translation

#167 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#174 Replacing l18n toml files to json
  CONTRIBUTING.md
  i18n/ar.json
  i18n/ar.toml
  i18n/ca.toml
  i18n/de.json
  i18n/de.toml
  i18n/en.json
  i18n/en.toml
  i18n/es.json
  i18n/es.toml
  i18n/fa.json
  i18n/fa.toml
  i18n/fr.json
  i18n/fr.toml
  i18n/id.json
  i18n/id.toml
  i18n/it.json
  i18n/it.toml
  i18n/ja.json
  i18n/ja.toml
  i18n/ko.json
  i18n/ko.toml
  i18n/lv.json
  i18n/lv.toml
  i18n/nb-NO.toml
  i18n/nl.json
  i18n/nl.toml
  i18n/pl.json
  i18n/pl.toml
  i18n/pt-BR.json
  i18n/pt-BR.toml
  i18n/pt-PT.json
  i18n/pt-PT.toml
  i18n/ru.json
  i18n/ru.toml
  i18n/sv.toml
  i18n/tr.json
  i18n/tr.toml
  i18n/uk.toml
  i18n/vi.json
  i18n/vi.toml
  i18n/zh-CN.json
  i18n/zh-CN.toml
  i18n/zh-HK.json
  i18n/zh-HK.toml
  i18n/zh-TW.json
  i18n/zh-TW.toml
Labels: enhancement

#172 Implement RSS
  config.toml
  layouts/_default/rss.xml
  layouts/partials/head/head.html
Labels: enhancement

#135 wip: feat: implement static content
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .vscode/launch.json
  assets/css/main.css
  config.toml
  content/about/index.md
  content/posts/community-update-december-2020.md
  layouts/404.html
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/_default/rss.xml
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/footer/footer.html
  layouts/partials/head/head.html
  layouts/partials/head/languages.html
  layouts/partials/meta/site-twittercard.html
  layouts/partials/navbar.html
  package-lock.json
  package.json
  postcss.config.js
  static/fonts/rocky-font.css
  tailwind.config.js
Labels: priority: high, tag: content, type: enhancement
