Repository rocky-linux/rockylinux.org, pull requests merged in 2021-11, with the labels that each got.

#86 Chinese (Hong Kong) translation completed (updated)
  src/i18n/locales/zh-hk/translation.json
Labels: priority: low, status: peer review needed, type: maintenance

#89 ca - add missing strings and fix some typos
  src/i18n/locales/ca/translation.json
Labels: priority: low, status: peer review needed, type: maintenance

#95 Updated Swedish Translation for the Website
  src/i18n/locales/sv/translation.json
Labels: priority: low, status: peer review needed, type: maintenance

#127 Translate missing things.
  src/i18n/locales/pl/translation.json
Labels: priority: low, status: peer review needed, type: maintenance

#128 First translated to Polish version.
  src/i18n/locales/pl/download.json
Labels: priority: low, status: peer review needed, type: maintenance

#129 First Polish translation.
  src/i18n/locales/pl/partners.json
Labels: priority: low, status: peer review needed, type: maintenance

#130 First Polish language sponsors version.
  src/i18n/locales/pl/sponsors.json
Labels: priority: low, status: peer review needed, type: maintenance

#131 Polish translation of FAQ
  src/i18n/locales/pl/faq.json
Labels: priority: low, status: peer review needed, type: maintenance

#136 fix: changed german translations
  src/i18n/locales/de/index.json
Labels: priority: medium, status: peer review needed, tag: content, type: maintenance

#148 Update Indonesian translations
  src/i18n/locales/id/download.json
  src/i18n/locales/id/faq.json
  src/i18n/locales/id/index.json
  src/i18n/locales/id/partners.json
  src/i18n/locales/id/sponsors.json
  src/i18n/locales/id/translation.json
Labels: priority: low, status: peer review needed, tag: content, tag: help wanted, type: maintenance

#195 Update download.json to add some chinese simple translation
  src/i18n/locales/zh-cn/download.json
Labels: priority: low, status: peer review needed, tag: content, tag: help wanted, type: maintenance

#196 Fix Chinese translation.json file.
  src/i18n/locales/zh-cn/translation.json
Labels: priority: low, status: peer review needed, tag: content, tag: help wanted, type: maintenance
